# Generated by Django 6.0.3 on 2026-04-11 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivalapp', '0001_initial'),
        ('restauranteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField()),
                ('votos_totales', models.IntegerField(default=0)),
                ('fecha_publicacion', models.DateTimeField()),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='festivalapp.festival')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='restauranteapp.restaurante')),
            ],
            options={
                'db_table': 'resultado',
                'constraints': [models.UniqueConstraint(fields=('festival', 'posicion'), name='unique_resultado_festival_posicion'), models.UniqueConstraint(fields=('festival', 'restaurante'), name='unique_resultado_festival_restaurante')],
            },
        ),
    ]
