services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env

  frontend:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
