# Generated by Django 6.0.3 on 2026-04-11 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('votos_total', models.IntegerField(default=0)),
                ('comentarios_total', models.IntegerField(default=0)),
                ('porcentaje_votos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to='festivalapp.festival')),
            ],
            options={
                'db_table': 'restaurante',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plato', to='restauranteapp.restaurante')),
            ],
            options={
                'db_table': 'plato',
            },
        ),
    ]
