# Generated by Django 6.0.3 on 2026-04-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauranteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
