# Generated by Django 6.0.3 on 2026-04-11 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restauranteapp', '0001_initial'),
        ('usuarioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='restauranteapp.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarioapp.votante')),
            ],
            options={
                'db_table': 'comentario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='restauranteapp.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='usuarioapp.votante')),
            ],
            options={
                'db_table': 'voto',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'restaurante'), name='unique_voto_usuario_restaurante')],
            },
        ),
    ]
